// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD4hvwojTGTL0TObromh5qxWkOupYx4jE',
    appId: '1:448502233028:web:4beaee5532dfc36e3e5691',
    messagingSenderId: '448502233028',
    projectId: 'royalnest-d9de5',
    authDomain: 'royalnest-d9de5.firebaseapp.com',
    storageBucket: 'royalnest-d9de5.firebasestorage.app',
    measurementId: 'G-0ZCE95VYMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAqrWokRTi_9H9lFMI7YRclfu3QPIvnpo',
    appId: '1:448502233028:android:ab14cfddd466dfed3e5691',
    messagingSenderId: '448502233028',
    projectId: 'royalnest-d9de5',
    storageBucket: 'royalnest-d9de5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhtSY0ZDVB1tYMi-BnLY3VtqEe-S-LAqI',
    appId: '1:448502233028:ios:e9880f634d687c9c3e5691',
    messagingSenderId: '448502233028',
    projectId: 'royalnest-d9de5',
    storageBucket: 'royalnest-d9de5.firebasestorage.app',
    iosBundleId: 'com.example.fypRoyalnest',
  );
}
